project:
    type: tufte
book:
  title: |
    The emergence of\
    an Information Bottleneck Theory\
    of Deep Learning\
  # title-short used in the head, only way I found not to insert long title there
  title-short: $$~$$ # Q: Why blank space without mathmode didn't work?
  output-file: IBToDL
  author: Fred Guth
  publisher: Universidade de Brasília
  date: "20/02/2022"
  chapters:
    - index.qmd
    # - Front/copyright.qmd
    # - Front/dedication.qmd
    # - Front/ack.qmd
    # - Front/epigraph.qmd
    - Chapters/context.qmd
    - part: Background
      chapters:
        - Chapters/ai.qmd
    #     - Chapters/prob.qmd
    #     - Chapters/mlt.qmd
    #     - Chapters/info.qmd
    # - part: intermezzo.qmd
    # - part: A new theory
    #   chapters: 
    #     - Chapters/ib-method.qmd
    #     - Chapters/ib-rl.qmd
    #     - Chapters/ib-dl.qmd
    # - Chapters/conclusion.qmd
    # - Back/notation.qmd
    # - Back/acronyms.qmd
    # - Back/colophon.qmd
    # - part: Development
    #   chapters:
    #   - Back/quarto-questions.qmd

format:
    pdf:
      classoption: ["12pt", "british"]
      include-in-header:
        - Tex/math_commands.tex
bibliography: bibliography.bib
  

  # cover: "Images/cover.pdf"
  # coversheet: "Images/coversheet.pdf"

