project:
    type: tufte
book:
  title: |
    The emergence of\
    an Information Bottleneck Theory\
    of Deep Learning\
  # title-short used in the head, only way I found not to insert long title there
  title-short: $$~$$ # Q: Why blank space without mathmode didn't work?
  output-file: IBToDL
  author: Fred Guth
  publisher: Universidade de Brasília
  date: "20/02/2022"
  chapters:
    - index.qmd
    # - Front/copyright.qmd
    # - Front/dedication.qmd
    # - Front/ack.qmd
    # - Front/epigraph.qmd
    - Chapters/context.qmd
    - part: Background
      chapters:
        - Chapters/ai.qmd
    #     - Chapters/prob.qmd
    #     - Chapters/mlt.qmd
    #     - Chapters/info.qmd
    # - part: intermezzo.qmd
    # - part: A new theory
    #   chapters: 
    #     - Chapters/ib-method.qmd
    #     - Chapters/ib-rl.qmd
    #     - Chapters/ib-dl.qmd
    # - Chapters/conclusion.qmd
    # - Back/notation.qmd
    # - Back/acronyms.qmd
    # - Back/colophon.qmd
    - part: Tufte-Quarto
      chapters:
      - Back/quarto-questions.qmd
      - Back/todo.qmd

format: # specific to my dissertation
    html:
      html-math-method: mathjax
      include-in-header:
        - text: |
            <script>
              window.MathJax = {
                loader: {
                  load: ['[tex]/bm', '[tex]/bigints', '[tex]/nicefrac', '[tex]/venndiagram', '[tex]/xpatch']
                },
                tex: {
                  packages: {'[+]': ['bm', 'bigints', 'nicefrac', 'venndiagram', 'xpatch']}
                }
              };
            </script>
        - "Tex/_dollar.tex" # hack for macros in html https://github.com/quarto-dev/quarto-cli/discussions/2845
        - "Tex/math_macros.tex"
        - "Tex/_dollar.tex" # hack for macros in html https://github.com/quarto-dev/quarto-cli/discussions/2845
    pdf:
      classoption: ["12pt", "british"]
      include-in-header:
        - Tex/math_commands.tex
bibliography: bibliography.bib


  # cover: "Images/cover.pdf"
  # coversheet: "Images/coversheet.pdf"

